name: Unit and Functional Tests

on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: atsdk Unit CTest
        run: |
          ./tools/run_ctest.sh

  functional-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Load secrets
        working-directory: tests/functional_tests
        run: |
          mkdir -p ~/.atsign/keys/
          echo "${{ secrets.ATKEYS_12ALPACA }}" > ~/.atsign/keys/@12alpaca_key.atKeys
          echo "${{ secrets.ATKEYS_12SNOWBOATING }}" > ~/.atsign/keys/@12snowboating_key.atKeys

      - name: Build and Run Functional Tests
        working-directory: tests/functional_tests
        run: |
          tools/run_ctest.sh
  build-examples:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Install atSDK
        run: |
          tools/install.sh

      - name: Build at_talk
        working-directory: examples/desktop/at_talk
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Build all CRUD examples
        working-directory: examples/desktop/crud
        run: |
          cmake -S . -B build -DTARGET_SRC=delete.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=get_publickey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=get_selfkey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=get_sharedkey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=put_publickey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=put_selfkey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=put_sharedkey.c && cmake --build build
      
      - name: Build events
        working-directory: examples/desktop/events
        run: |
          cmake -S . -B build
          cmake --build build
      
      - name: Build pkam_authenticate
        working-directory: examples/desktop/pkam_authenticate
        run: |
          cmake -S . -B build
          cmake --build build
      
      - name: Build REPL
        working-directory: examples/desktop/repl
        run: |
          cmake -S . -B build
          cmake --build build --target install