name: Unit and Functional Tests

on:
  workflow_dispatch:
  push:
    branches: [trunk]
  pull_request:
    branches: [trunk]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  unit-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: atsdk Unit CTest
        run: |
          cmake -S . -B build -DATSDK_BUILD_TESTS=ON -DCMAKE_EXPORT_COMPILE_COMMANDS=ON 
          cmake --build build --target all
          ctest --test-dir build/packages/atchops/tests --output-on-failure --timeout 2
          ctest --test-dir build/packages/atclient/tests --output-on-failure --timeout 2

  functional-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Load secrets
        working-directory: tests/functional_tests
        run: |
          mkdir -p ~/.atsign/keys/
          echo "${{ secrets.ATKEYS_12ALPACA }}" > ~/.atsign/keys/@12alpaca_key.atKeys
          echo "${{ secrets.ATKEYS_12SNOWBOATING }}" > ~/.atsign/keys/@12snowboating_key.atKeys

      - name: Install atSDK
        run: |
          cmake -S . -B build
          sudo cmake --build build --target install

      - name: Build and Run Functional Tests
        working-directory: tests/functional_tests
        run: |
          cmake -S . -B build
          cmake --build build
          ctest --test-dir build -VV --timeout 60

  build-examples:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Install atSDK
        run: |
          cmake -S . -B build
          sudo cmake --build build --target install

      - name: Build at_talk
        working-directory: examples/desktop/at_talk
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Build all CRUD examples
        working-directory: examples/desktop/crud
        run: |
          cmake -S . -B build -DTARGET_SRC=delete.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=get_publickey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=get_selfkey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=get_sharedkey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=put_publickey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=put_selfkey.c && cmake --build build
          cmake -S . -B build -DTARGET_SRC=put_sharedkey.c && cmake --build build
      
      - name: Build events
        working-directory: examples/desktop/events
        run: |
          cmake -S . -B build
          cmake --build build
      
      - name: Build pkam_authenticate
        working-directory: examples/desktop/pkam_authenticate
        run: |
          cmake -S . -B build
          cmake --build build
      
      - name: Build REPL
        working-directory: examples/desktop/repl
        run: |
          cmake -S . -B build
          cmake --build build

      - name: Build reconnection example
        working-directory: examples/desktop/reconnection
        run: |
          cmake -S . -B build
          cmake --build build --target install

      - name: Build sample cmake project
        working-directory: examples/desktop/sample_cmake_project
        run: |
          cmake -S . -B build -Datsdk="/usr/local/bin/cmake/atsdk"
          cmake --build build